### PR TITLE
Translate webgpu-memory-layout.md into korean

### PR DESCRIPTION
**Pull request by Shubidumdu**

### CODE REVIEW

**Comment by greggman** [comment]
please remove the js file. Thanks. It should use the existing one. There was a bug in the builder I fixed just a few moments ago.

**Comment by Shubidumdu** [comment]
I removed it and modifed script's src path. Thanks. :)

**Comment by greggman** [comment]
You should put the path back so it's the same as the english. Then commit that. Then

```
git fetch https://github.com/gfxfundamentals/webgpufundamentals.git main
git rebase FETCH_HEAD
npm ci
npm run build
npm start
```

That should work I hope.

**Comment by Shubidumdu** [comment]
It works great, thanks! 👍

**Pull request merged**
