### PR TITLE
Translate webgpu-fundamentals to chinese.

### PR DESCRIPTION
**Pull request by swpuhu**
Translate webgpu-fundamentals to chinese.

### CODE REVIEW

**Comment by greggman** [comment]
Thank you the translation. Please remove the .js file. Those do not need to be copied. Thanks

**Comment by swpuhu** [comment]
.js file has been removed. But the path of "webgpu-fundamentals.js" seems to be error  so that cannot display the example of rasterization.

**Comment by swpuhu** [comment]
> Thank you the translation. Please remove the .js file. Those do not need to be copied. Thanks
@greggman 
.js file has been removed. But the path of "webgpu-fundamentals.js" seems to be error so that cannot display the example of rasterization.

**Comment by greggman** [comment]
Sorry, it was a bug in the builder. fixed.

**Pull request merged**
